[package]
name = "lab-flow"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "git-lab"
path = "src/main.rs"

[dependencies]
regex = "1.5.6"